consul:
  CONSUL_IP: ''
  CONSUL_PORT: '8500'
log:
  backupcount: 2
  filename: /var/log/middleware/worker.log
  level: info
  maxbytes: 5242880
rabbitmq:
  RABBIT_MQ_IP: localhost
  RABBIT_MQ_PASSWORD: Password1
  RABBIT_MQ_USERNAME: admin
servicenow:
  SERVICENOW_USERNAME: ''
  SERVICENOW_PASSWORD: ''
vulnerability:
  VSCAN_SERVER_PASSWORD: xStream2018!
  VSCAN_SERVER_URL: https://100.64.128.30
  VSCAN_SERVER_USERNAME: xad_user
workers:
  no_of_proc: 3
xstream:
  XSTREAM_KEY: ''
  XSTREAM_SECRET: ''
