# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: '{{ step }} - Configure Firewalls'
    hosts: all_windows_servers
    tags:
        - '{{ step }} - Configure Firewalls'
    tasks:

#        -
#            name: '{{ step }} - Enable Firewall'
##            tags:
##              -   '{{ step }} - Enable Firewall'
#            delegate_to: localhost
#            ehc_script_agent:
#                package_name: common
#                module_name: configFirewall
#                method_name: enableFirewall
#                method_params:
#                    vCenterDict: '{{ vcenter }}'
#                    VMDict: '{{ vmDict }}'
#            register: enableFirewallResults
#            failed_when: not enableFirewallResults.data is defined or enableFirewallResults.data.err_message is defined or enableFirewallResults.data.status == false
#            changed_when: enableFirewallResults.data is defined and not enableFirewallResults.data.err_message is defined and enableFirewallResults.data.status == true

        -
            name: '{{ step }} - Validate Configure Firewalls'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vra
                module_name: configureIAASFirewall
                method_name: validateFirewallRulesForIaaSComponet
                method_params:
                    vCenterDict: '{{ vcenter }}'
                    vmDict: '{{ vmDict }}'
                    componentType: '{{ componentType }}'
            register: validateFirewallRulesForIaaSComponetResults
            failed_when: not validateFirewallRulesForIaaSComponetResults.data is defined or validateFirewallRulesForIaaSComponetResults.data.err_message is defined or validateFirewallRulesForIaaSComponetResults.data.status == false
            changed_when: validateFirewallRulesForIaaSComponetResults.data is defined and not validateFirewallRulesForIaaSComponetResults.data.err_message is defined and validateFirewallRulesForIaaSComponetResults.data.status == true
            ignore_errors: validateFirewallRulesForIaaSComponetResults.failed_when_result

        -
            name: '{{ step }} - Configure Firewalls'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vra
                module_name: configureIAASFirewall
                method_name: configureFirewallRulesForIaaSComponet
                method_params:
                    vCenterDict: '{{ vcenter }}'
                    vmDict: '{{ vmDict }}'
                    componentType: '{{ componentType }}'
            register: configureFirewallRulesForIaaSComponet
            failed_when: not configureFirewallRulesForIaaSComponet.data is defined or configureFirewallRulesForIaaSComponet.data.err_message is defined or configureFirewallRulesForIaaSComponet.data.status == false
            changed_when: configureFirewallRulesForIaaSComponet.data is defined and not configureFirewallRulesForIaaSComponet.data.err_message is defined and configureFirewallRulesForIaaSComponet.data.status == true
            # when: validateFirewallRulesForIaaSComponetResults.failed_when_result

        -
            name: '{{ step }} - Post Validate Configure Firewalls'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vra
                module_name: configureIAASFirewall
                method_name: validateFirewallRulesForIaaSComponet
                method_params:
                    vCenterDict: '{{ vcenter }}'
                    vmDict: '{{ vmDict }}'
                    componentType: '{{ componentType }}'
            register: postValidateFirewallRulesForIaaSComponetResults
            failed_when: not postValidateFirewallRulesForIaaSComponetResults.data is defined or postValidateFirewallRulesForIaaSComponetResults.data.err_message is defined or postValidateFirewallRulesForIaaSComponetResults.data.status == false
            changed_when: postValidateFirewallRulesForIaaSComponetResults.data is defined and not postValidateFirewallRulesForIaaSComponetResults.data.err_message is defined and postValidateFirewallRulesForIaaSComponetResults.data.status == true
            when: not configureFirewallRulesForIaaSComponet|skipped