# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: 'NSX - {{ step }} - Poll Loadbalancer Edges'
    hosts: '{{ vms }}'
    tags:
                - 'NSX - {{ step }} - Poll Loadbalancer Edges'
    tasks:
        -
            name: 'NSX - {{ step }} - Get Loadbalancer Edge ID'
            delegate_to: localhost
            ehc_script_agent:
                package_name: nsx
                module_name: configureLoadBalancer
                method_name: getEdgeId
                method_params:
                    nsxManager: '{{ nsxManager }}'
                    edgeName: '{{ nsx_load_balancer_load_balancer_name }}'
            register: edgeId

        -
            name: 'NSX - {{ step }} - Poll Loadbalancer Edges'
            delegate_to: localhost
            ehc_script_agent:
                package_name: nsx
                module_name: pollLoadBalancerEdge
                method_name: pollLoadBalancerEdge
                method_params:
                    nsxDict: '{{ nsxManager }}'
                    edgeId: '{{ edgeId.data }}'
            register: pollLoadBalancerEdgeResults
            failed_when: not pollLoadBalancerEdgeResults.data is defined or pollLoadBalancerEdgeResults.data.err_message is defined or not pollLoadBalancerEdgeResults.data.status == true
            changed_when: pollLoadBalancerEdgeResults.data is defined and not pollLoadBalancerEdgeResults.data.err_message is defined and pollLoadBalancerEdgeResults.data.status == true
            until: pollLoadBalancerEdgeResults.data is defined and not pollLoadBalancerEdgeResults.data.err_message is defined and pollLoadBalancerEdgeResults.data.status == true