# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: '{{ step|default(None) }} - {{ snapshot_name }} - Revert - {{ description }}'
    hosts: '{{ vms }}'
    tags:
        - '{{ step|default(None) }} - {{ snapshot_name }} - Revert - {{ description }}'
    gather_facts: no
    any_errors_fatal: True
    tasks:
        -
            name: '{{ step|default(None) }} - Revert to Snapshot'
            delegate_to: localhost
            ehc_script_agent:
                package_name: common
                module_name: ISnapshot
                method_name: revertSnapshot
                method_params:
                    vCenterDict: '{{ vcenter }}'
                    snapshotName: '{{ snapshot_name }}'
                    vmDict:
                        vmname: '{{ vmname }}'
            register: revertResult
            failed_when:  not revertResult.data is defined or revertResult.data.err_message is defined
            changed_when:  revertResult.data is defined and not revertResult.data.err_message is defined
#
#        -
#            name: '{{ step|default(None) }} - Power on VMs'
#            delegate_to: localhost
#            ehc_script_agent:
#                package_name: common
#                module_name: IVMManagement
#                method_name: powerOnVM
#                method_params:
#                    vCenterDict: '{{ vcenter }}'
#                    vmDict:
#                        vmname: '{{ vmname }}'
#            register: powerOnVMResult
#            failed_when:  not powerOnVMResult.data is defined or powerOnVMResult.data.err_message is defined
#            changed_when:  powerOnVMResult.data is defined and not powerOnVMResult.data.err_message is defined
#            ignore_errors: True
#
#        -
#            name: '{{ step|default(None) }} - Wait for all servers to be up'
#            delegate_to: localhost
#            ehc_script_agent:
#                package_name: ozone
#                method_name: ensureGuestToolsRunningOnVM
#                module_name: vmUtils
#                method_params:
#                    vCentreDict: '{{ vcenter }}'
#                    vmDict:
#                        vmname: '{{ vmname }}'
#            register: result
#            failed_when: not result.data is defined and result.data.err_message is defined
#            changed_when: result.data is defined and not result.data.err_message is defined
#            ignore_errors: True