# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

ansible_connection: ssh

ovaType: 'NSX_Manager'
ovaVersion: '6.2'

ova_manifest_lookup: '{{ sw_repository_manifest.content.nsx_manager_ova }}'
ovaSource: '{{ sw_repository_manifest.base_path }}/{{ ova_manifest_lookup.relative_path }}/{{ ova_manifest_lookup.file_name }}'

nsxOva:
    vmName: '{{ vmname }}'
    ovaPath: '{{ ovaSource }}'
    vmNetwork: '{{ vcenter_network }}'
    hostname: '{{ ansible_host }}'
    ip: '{{ ansible_host_ip }}'
    netmask: '{{ common.management_network_netmask }}'
    gateway: '{{ common.management_network_gateway }}'
    dnsServer: '{{ common.dns_server_ip }}'
    dnsDomain: '{{ ad_domain }}'
    ntp: '{{ common.ntp_servers_comma_separated }}'
    adminUserPassword: '{{ nsx_manager_info.admin_user_password }}'
    cliUserPassword: '{{ nsx_manager_info.cli_user_password }}'

ovaConfigDict:
    network: '{{ vcenter_network }}'
    hostname: '{{ ansible_host }}'
    ip: '{{ ansible_host_ip }}'
    netmask: '{{ common.management_network_netmask }}'
    gateway: '{{ common.management_network_gateway }}'
    dns_server: '{{ common.dns_server_ip }}'
    dns_domain: '{{ ad_domain }}'
    ntp: '{{ common.ntp_servers_comma_separated }}'
    ssh_enabled: True
    cli_enabled: True
    cli_admin_password: '{{ nsx_manager_info.admin_user_password }}'
    cli_privilege_password: '{{ nsx_manager_info.cli_user_password }}'

nsxManager:
    host: '{{ host_address.nsx_manager.ip }}'
    userName: admin
    username: admin
    password: '{{ nsx_manager_info.admin_user_password }}'

ehc_nsx_ent_admin:
    userName: '{{ ad_user.ehc_nsx_ent_admin.username }}@{{ ad_domain }}'
    username: '{{ ad_user.ehc_nsx_ent_admin.username }}@{{ ad_domain }}'
    password: '{{ ad_user.ehc_nsx_ent_admin.password }}'

nsxDeployvCenter:
    vCenterIPAddress: '{{ vcenter.ip }}'
    vCenterUsername: '{{ vcenter.username }}'
    vCenterPassword: '{{ vcenter.password }}'
    datastore: '{{ vcenter_datastore }}'
    cluster: '{{ vcenter_cluster }}'
    hostName: '{{ vcenter_ovadeployhost }}'
    dataCenter: '{{ vcenter_datacenter }}'

deploy_args:
    package_name: common
    module_name: vCenterOps
    method_name: deployOVA
    method_params:
        vCenterData:
            vCenterIPAddress: '{{ vcenter.host }}'
            vCenterUsername: '{{vcenter.username}}'
            vCenterPassword: '{{vcenter.password}}'
            datastore: '{{  vcenter_datastore  }}'
            cluster: '{{ vcenter_cluster }}'
            dataCenter: '{{ vcenter_datacenter }}'
            resourcePool: '{{ resource_pools.core }}'
            hostName: '{{ vcenter_ovadeployhost }}'
            port: '443'
        vmData:
            vmName: '{{ vmname }}'
            powerState: "off"
            diskStorageFormat: '{{ vcenter_details.disk_mode }}'
        ovaDetails:
            type: '{{ ovaType }}'
            ovaSource: '{{ ovaSource }}'
            ovfConfigDict: '{{ ovaConfigDict }}'
        # deploymentType: 'ovftool'
        timeout: '{{ timeout_for_vm_deploy }}'

nsxLicenseParameters:
    licenseKey: '{{ license_key.nsx_manager }}'
    vCenterInfo:
        username: '{{ vcenter.username }}'