# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
# Playbook file: create-resource-pool.yml
-
    name: '{{ step }} - Create Resource Pools'
    hosts: '{{ vms }}'
    any_errors_fatal: true
    tags:
                - '{{ step }} - Create Resource Pools'
    tasks:
        -
            name: '{{ step }} - Pre-Validate Resource Pool'
            delegate_to: localhost
            run_once: true
            ehc_script_agent:
                package_name: vcenter
                module_name: createResourcePool
                method_name: validateResourcePool
                method_params:
                    vCenterInfo: '{{ vcenter }}'
                    cluster: '{{ vcenter_cluster }}'
                    resourcePool: '{{ item }}'
            register: validateResourcePoolResults
            failed_when: validateResourcePoolResults.data is not defined or validateResourcePoolResults.data.err_message is defined or not validateResourcePoolResults.data.status == true
            changed_when: validateResourcePoolResults.data is defined and validateResourcePoolResults.data.err_message is not defined and validateResourcePoolResults.data.status == true
            with_items: '{{ resource_pools|json_query("*") }}'
            ignore_errors: validateResourcePoolResults.failed_when_result

        -
            name: '{{ step }} - Create Resource Pool'
            delegate_to: localhost
            run_once: true
            ehc_script_agent:
                package_name: vcenter
                module_name: createResourcePool
                method_name: createResourcePool
                method_params:
                    vCenterInfo: '{{ vcenter }}'
                    cluster: '{{ vcenter_cluster }}'
                    resourcePool: '{{ item.0 }}'
            register: createResourcePoolResults
            failed_when: createResourcePoolResults.data is not defined or createResourcePoolResults.data.err_message is defined or not createResourcePoolResults.data.status == true
            changed_when: createResourcePoolResults.data is defined and createResourcePoolResults.data.err_message is not defined and createResourcePoolResults.data.status == true
            with_together:
              -   '{{ resource_pools|json_query("*") }}'
              -   '{{ validateResourcePoolResults.results }}'
            when: item.1.failed_when_result
            ignore_errors: True

        -
            name: '{{ step }} - Post Validate Resource Pool'
            delegate_to: localhost
            run_once: true
            ehc_script_agent:
                package_name: vcenter
                module_name: createResourcePool
                method_name: validateResourcePool
                method_params:
                    vCenterInfo: '{{ vcenter }}'
                    cluster: '{{ vcenter_cluster }}'
                    resourcePool: '{{ item.0 }}'
            register: postValidateResourcePoolResults
            failed_when: postValidateResourcePoolResults.data is not defined or postValidateResourcePoolResults.data.err_message is defined or not postValidateResourcePoolResults.data.status == true
            changed_when: postValidateResourcePoolResults.data is defined and postValidateResourcePoolResults.data.err_message is not defined and postValidateResourcePoolResults.data.status == true
            with_together:
              -   '{{ resource_pools|json_query("*") }}'
              -   '{{ createResourcePoolResults.results }}'
            when: not item.1|skipped
