# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
# Playbook File -Master-EHC-41-Deploy-and-Configure.yml

- include: playbooks/validation/main.yml  ignore_errors=True
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-150-reset-environment
- include: playbooks/deploy/main.yml
- include: playbooks/backup_and_restore/bpb-150-deploy-automation.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-500-rollback-configure-vrops
- include: playbooks/vrops/epb-500-configure-vrops.yml
- include: playbooks/backup_and_restore/bpb-500-configure-vrops.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-200-rollback-vcenter-and-nsx
- include: playbooks/vcenter/main.yml
- include: playbooks/backup_and_restore/bpb-200-configure-vcenter-and-nsx.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-250-rollback-sql
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 200" subject="PROGRESS UPDATE - EHC Automated Install Update - vCenter Configured!" textInMail="The EHC Automated Install has finished configuring vCenter servers. Next - SQL Configuration." ignore_errors=True
- include: playbooks/sql/main.yml
- include: playbooks/backup_and_restore/bpb-250-configure-sql.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-350-rollback-configure-vro
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 350" subject="PROGRESS UPDATE - EHC Automated Install Update - SQL Configured!" textInMail="The EHC Automated Install has finished configuring SQL servers. Next - vRO Configuration." ignore_errors=True
- include: playbooks/vro/epb-350-configure-vro.yml
- include: playbooks/backup_and_restore/bpb-350-configure-vro.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-400-rollback-configure-vro
- include: playbooks/vro/epb-400-configure-vro.yml
- include: playbooks/backup_and_restore/bpb-400-configure-vro.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-450-rollback-configure-vra
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 400" subject="PROGRESS UPDATE - EHC Automated Install Update - VRO Configured!" textInMail="The EHC Automated Install has finished configuring vRealize Orchestrator servers. Next - vRA Configuration." ignore_errors=True
- include: playbooks/vra/main.yml
- include: playbooks/backup_and_restore/bpb-450-configure-vra.yml
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 450" subject="PROGRESS UPDATE - EHC Automated Install Update - VRA Configured!" textInMail="The EHC Automated Install has finished configuring vRealize Automation. Next - vROPS Configuration." ignore_errors=True
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-550-rollback-configure-vrops
- include: playbooks/vrops/epb-550-configure-vrops-data-nodes.yml
- include: playbooks/vrops/epb-550-configure-vrops-remote-nodes.yml
- include: playbooks/backup_and_restore/bpb-550-configure-vrops.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-600-rollback-configure-vrb
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 550" subject="PROGRESS UPDATE - EHC Automated Install Update - vROPS Configured!" textInMail="The EHC Automated Install has finished configuring vRealize Operations. Next - vRB Configuration." ignore_errors=True
- include: playbooks/vrb/main.yml
- include: playbooks/backup_and_restore/bpb-600-configure-vrb.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-650-rollback-configure-loginsight
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 600" subject="PROGRESS UPDATE - EHC Automated Install Update - vRB Configured!" textInMail="The EHC Automated Install has finished configuring vRealize Business. Next - vRLI Configuration." ignore_errors=True
- include: playbooks/vrli/main.yml
- include: playbooks/backup_and_restore/bpb-650-configure-vrli.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-700-rollback-deploy-configure-ehc-foundation
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 650" subject="PROGRESS UPDATE - EHC Automated Install Update - vRLI Configured!" textInMail="The EHC Automated Install has finished configuring vRealize Log Insight. Next - EHC Foundation Configuration." ignore_errors=True
- include: playbooks/vro/epb-700-deploy-configure-ehc-foundation.yml
- include: playbooks/backup_and_restore/bpb-700-deploy-configure-ehc-foundation.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-750-rollback-configure-vra
- include: playbooks/vra/plays/apply-branding.yml
- include: playbooks/backup_and_restore/bpb-750-configure-vra.yml
- include: playbooks/backup_and_restore/plays/update-rollback-point.yml rollback_point=rpb-800-rollback-firewalls
- include: playbooks/validation/plays/pre-validation-smtp.yml step="NTF - 700" subject="PROGRESS UPDATE - EHC Automated Install Update - EHC Foundations Configured!" textInMail="The EHC Automated Install has finished configuring EHC Foundation and Branding packages. Next - Firewall Configuration and Cleanup." ignore_errors=True
- include: playbooks/firewall/configure-firewalls.yml
- include: playbooks/deploy/set-drs-level-to-fully-automated.yml
- include: playbooks/cleanup/main.yml