# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
# Playbook file: vcenter/main.yml

-
    include:  plays/poll-psc.yml
    vars:
        step: PSC01 - EPB-200-010
        vms: psc01
        description: Poll

-
    include:  plays/toggle-ssh.yml
    vars:
        step: PSC01 - EPB-200-015
        vms: psc01
        ssh_enable: True

-
    include:  plays/set-default-shell-for-appliance.yml
    vars:
        step: PSC01 - EPB-200-020
        vms: psc01
        description: Set Appliance Default Shell

-
    include:  plays/import-psc-ssl-certs.yml
    vars:
        step: PSC01 - EPB-200-030
        vms: psc01
        vCenterRebootNeeded: True
        description: Import Machine SSL and Solution Certificates

-
    include:  plays/toggle-ssh.yml
    vars:
        step: PSC01 - EPB-200-035
        vms: psc01
        ssh_enable: False

-
    include:  plays/deploy-psc.yml
    vars:
        step: VCN - PSC02 - EPB-200-040
        vms: psc02
        partnerPscDict: '{{ hostvars["psc01"].vmDict }}'
        description: Deploy And Configure
        resource_pool: '{{ resource_pools.core }}'

-
    include:  plays/poll-psc.yml
    vars:
        step: PSC02 - EPB-200-050
        vms: psc02
        description: Poll
        vcenter_folderPath: ''

-
    include:  plays/set-default-shell-for-appliance.yml
    vars:
        step: PSC02 - EPB-200-060
        vms: psc02
        description: Set Appliance Default Shell

-
    include:  plays/import-psc-ssl-certs.yml
    vars:
        step: PSC02 - EPB-200-070
        vms: psc02
        description: Import Machine SSL and Solution Certificates

-
    include:  plays/configure-ntp.yml
    vars:
        step: PSC02 - EPB-200-071
        vms: psc02
        description: Configure NTP on PSC

-
    include:  plays/toggle-ssh.yml
    vars:
        step: PSC02 - EPB-200-075
        vms: psc02
        ssh_enable: False

-
    include:  ../backup_and_restore/plays/poll-vcenter.yml
    vars:
        step: VCN - EPB-200-080
        vms: vcenter_server

-
    include:  plays/toggle-ssh.yml
    vars:
        step: VCN - EPB-200-085
        vms: vcenter_server
        ssh_enable: True

-
    include:  plays/import-vcenter-ssl-certs.yml
    vars:
        step: VCN - EPB-200-090
        vms: vcenter_server
        description: vCenter - SSL Certificates Replacement

-
    include:  plays/toggle-ssh.yml
    vars:
        step: VCN - EPB-200-095
        vms: vcenter_server
        ssh_enable: False

-
    include:  plays/configure-sso-groups-roles.yml

-
    include:  ../nsx/main.yml

-
    include:  plays/deploy-psc.yml
    vars:
        step: VCN - APSC01 - EPB-200-220
        vms: autopsc01
        partnerPscDict: '{{ hostvars["psc02"].vmDict }}'
        description: AUTOPSC01 - Depoloy And Configure
        resource_pool: '{{ resource_pools.auto }}'

-
    include:  plays/poll-psc.yml
    vars:
        step: APSC01 - EPB-200-230
        vms: autopsc01
        description: AUTOPSC01 - Poll
        vcenter_folderPath: ''

-
    include:  plays/set-default-shell-for-appliance.yml
    vars:
        step: APSC01 - EPB-200-240
        vms: autopsc01
        description: AUTOPSC01 - Set Appliance Default Shell

-
    include:  plays/import-psc-ssl-certs.yml
    vars:
        step: APSC01 - EPB-200-250
        vms: autopsc01
        description: AUTOPSC01 - Import Machine SSL and Solution Certificates

-
    include:  plays/configure-ntp.yml
    vars:
        step: APSC01 - EPB-200-251
        vms: autopsc01
        description: Configure NTP on PSC

-
    include:  plays/toggle-ssh.yml
    vars:
        step: APSC01 - EPB-200-255
        vms: autopsc01
        ssh_enable: False

-
    include:  plays/configure-sso-replication-agreement.yml
    vars:
        step: APSC01 - EPB-200-260
        vms: autopsc01
        description: AUTOPSC01 - Configure SSO Replication Agreement

-   include: ../vrops/plays/configure-monitor-vcenter.yml step=EPB-200-270

-   include: plays/configure-role-for-vrb.yml step=EPB-200-280

-
    include:  ../vrli/install-vrli-agent.yml
    vars:
        step: VCN - EPB-200-290
        vms: vcenter_server
        log_insight_agent_file_path: '{{ hostvars["log_insight"].log_insight_linux_agent_file }}'

-
    include:  plays/create-sso-groups.yml
    vars:
      step: EPB-200-300