# ------------------------------------------------------------------------------
# Copyright (C) 2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------
---
-
    name: '{{ step }} - Validate Data Domain Server Entries'
    hosts: localhost
    gather_facts: no
    any_errors_fatal: True
    tags:
        -  '{{ step }} - Validate Data Domain Server Entries'
    tasks:
        -
            name: '{{ step }} - Validate Data Domain Local Server Entries'
            when: '{{ host_address.data_domain_server.fqdn != "" and
                      host_address.data_domain_server.ip != "" and
                      host_address.data_domain_server.vmname != "" and
                      host_address.data_domain_server.portgroup2 != "" and
                      host_address.data_domain_server.portgroup1 != "" }}'
            debug: msg="Data Domain Server Entries Validated"
            with_dict: '{{ host_address.data_domain_server }}'

        -
            name: '{{ step }} - Validate DNS Entry'
            when: '{{ common.primary_dns != "" and common.secondry_dns != "" }}'
            with_dict: '{{ common }}'
            debug: msg="Avamar Server Certificate Path Entry Validated"

