# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: 'NSX - {{ step }} - Create Admin Group for NSX'
    hosts: '{{ vms }}'
    tags:
                - 'NSX - {{ step }} - Create Admin Group for NSX'
    tasks:
        -
            name: 'NSX - {{ step }} - Validate Create Admin Group for NSX'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vcenter
                module_name: createAdminGroupForNSX
                method_name: validateAdminGroupForNSX
                method_params:
                    nsxHost: '{{ ansible_host_ip }}'
                    vcenterCred: '{{ vcenter }}'
                    adminGroupName: '{{ nsx_manager_info.enterprise_admin_group }}@{{ ad_domain }}'
            register: validateAdminGroupForNSXResults
            failed_when: not validateAdminGroupForNSXResults.data is defined or validateAdminGroupForNSXResults.data.err_message is defined or validateAdminGroupForNSXResults.data == false
            changed_when: validateAdminGroupForNSXResults.data is defined and not validateAdminGroupForNSXResults.data.err_message is defined and validateAdminGroupForNSXResults.data == true
            ignore_errors: validateAdminGroupForNSXResults.failed_when_result

        -
            name: 'NSX - {{ step }} - Create Admin Group for NSX'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vcenter
                module_name: createAdminGroupForNSX
                method_name: createAdminGroupForNSX
                method_params:
                    nsxHost: '{{ ansible_host_ip }}'
                    vcenterCred: '{{ vcenter }}'
                    adminGroupName: '{{ nsx_manager_info.enterprise_admin_group }}@{{ ad_domain }}'
            register: createAdminGroupForNSXResults
            failed_when: not createAdminGroupForNSXResults.data is defined or createAdminGroupForNSXResults.data.err_message is defined or createAdminGroupForNSXResults.data == false
            changed_when: createAdminGroupForNSXResults.data is defined and not createAdminGroupForNSXResults.data.err_message is defined and createAdminGroupForNSXResults.data == true
            when: validateAdminGroupForNSXResults.failed_when_result

        -
            name: 'NSX - {{ step }} - Post Validate Create Admin Group for NSX'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vcenter
                module_name: createAdminGroupForNSX
                method_name: validateAdminGroupForNSX
                method_params:
                    nsxHost: '{{ ansible_host_ip }}'
                    vcenterCred: '{{ vcenter }}'
                    adminGroupName: '{{ nsx_manager_info.enterprise_admin_group }}@{{ ad_domain }}'
            register: postValidateAdminGroupForNSXResults
            failed_when: not postValidateAdminGroupForNSXResults.data is defined or postValidateAdminGroupForNSXResults.data.err_message is defined or postValidateAdminGroupForNSXResults.data == false
            changed_when: postValidateAdminGroupForNSXResults.data is defined and not postValidateAdminGroupForNSXResults.data.err_message is defined and postValidateAdminGroupForNSXResults.data == true
            ignore_errors: not createAdminGroupForNSXResults|skipped
