# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-   include: plays/enable-firewalls.yml step="FWL - EPB-800-010"

-   include: plays/configure-firewalls.yml step="FWL - EPB-800-020"

-   include: ../backup_and_restore/plays/poll-sql-server.yml
    vars:
      vms: sql_server
      step: FWL - EPB-800-030

-   include: ../backup_and_restore/plays/poll-sql-db.yml
    vars:
      vms: sql_server
      dbName: '{{  databases.vro_database  }}'
      step: FWL - EPB-800-040

-   include: ../backup_and_restore/plays/poll-sql-db.yml
    vars:
      vms: sql_server
      dbName: '{{  databases.ehc_om_database  }}'
      step: FWL - EPB-800-050

-   include: ../backup_and_restore/plays/poll-sql-db.yml
    vars:
      vms: sql_server
      dbName: '{{  databases.vra_database  }}'
      step: FWL - EPB-800-060

-   include: ../backup_and_restore/plays/poll-vra-5480.yml
    vars:
      vms: vra_servers
      step: FWL - EPB-800-070

-   include: ../backup_and_restore/plays/poll-vra-web.yml
    vars:
      vms: vra_web_primary
      step: FWL - EPB-800-080

-   include: ../backup_and_restore/plays/poll-vra-manager.yml
    vars:
      vms: vra_manager_primary
      step: FWL - EPB-800-090

-   include: ../backup_and_restore/plays/poll-vra-dem.yml
    vars:
      vms: vra_worker_primary
      step: FWL - EPB-800-100

-   include: ../backup_and_restore/plays/poll-vra-agent.yml
    vars:
      vms: vra_proxy_agent_primary
      step: FWL - EPB-800-110

-   include: ../backup_and_restore/plays/poll-vra-app.yml
    vars:
      vms: vra_primary
      step: FWL - EPB-800-120