# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: '{{ step }} - Restart Primary vRO service'
    hosts: vro_primary
    gather_facts: no
    any_errors_fatal: True
    tasks:
        -
            name: '{{ step }} - Restart Primary vRO service'
            tags:
                - '{{ step }} - Restart Primary vRO service'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vro
                module_name: plugins
                method_name: restartServerService
                method_params:
                    vroInfo: '{{ vroInfo }}'
                    # TODO Check this timeout
                    timeout: 3600
            register: result
            changed_when: result.data is defined and result.data.err_message is not defined
            failed_when: result.data is not defined or result.data.err_message is defined