# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
-
    name: '{{ step }} - Pre Validation - vCenter NTP'
    hosts: localhost
    gather_facts: no
    any_errors_fatal: True
    tasks:
        -
            name: '{{ step }} - Validate vCenter NTP Configuration'
            tags:
                - '{{ step }} - Validate vCenter NTP Configuration'
            ehc_script_agent:
                package_name: common
                module_name: IVMManagement
                method_name: IvalidateNTPConfig
                method_params:
                  vCenterDict: '{{ vcenter }}'
                  vmDict: '{{ vcenter | combine({"username": "root"}) }}'
                  NTPServerList: '{{ ntp_servers }}'
            register: IvalidateNTPConfigResults
            failed_when: not IvalidateNTPConfigResults.data is defined or IvalidateNTPConfigResults.data.err_message is defined or not IvalidateNTPConfigResults.data == true
            changed_when: IvalidateNTPConfigResults.data is defined and not IvalidateNTPConfigResults.data.err_message is defined and IvalidateNTPConfigResults.data == true
            ignore_errors: '{{ ignore_errors|default(False) }}'