# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
-
    name: '{{ step }} - Pre Validation - Certificates'
    hosts: localhost
    gather_facts: no
    any_errors_fatal: True
    tags:
              - '{{ step }} - Validate and Convert SSL Certificates'
    tasks:
      -
          name: '{{ step }} - Upload Certs Config File'
          delegate_to: localhost
          ehc_script_agent:
              package_name: special
              module_name: update_config_file
              method_name: update_config_file
              method_params:
                  file_path: "{{ remote_certs_config_file }}"
                  file_contents: "{{lookup('template', local_certs_template_file, convert_data=False )}}"
          register: result
          failed_when: not result.data is defined or result.data.err_message is defined or result.data == false
          changed_when: result.data is defined and not result.data.err_message is defined and result.data == true
          ignore_errors: '{{ ignore_errors|default(False) }}'

      -
          name: '{{ step }} - Validate and Convert SSL Certificates'
          delegate_to: localhost
          ehc_script_agent:
              package_name: common
              module_name: certificateValidation
              method_name: validateUserCertificates
              method_params:
          register: validateUserCertResults
          failed_when: not validateUserCertResults.data is defined or validateUserCertResults.data.err_message is defined or false in validateUserCertResults.data|json_query('[].*[*][][].*[].*[]')
          changed_when: validateUserCertResults.data is defined and not validateUserCertResults.data.err_message is defined and false not in validateUserCertResults.data|json_query('[].*[*][][].*[].*[]')
          ignore_errors: '{{ ignore_errors|default(False) }}'
