# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
-
    name: '{{ step }} - Pre Validation - DNS'
    hosts: localhost
    gather_facts: no
    any_errors_fatal: True
    tasks:
        -
            name: '{{ step }} - Prepare DNS Entries for validation'
            tags:
                - '{{ step }} - Validate DNS Resolutions'
            vars:
                fqdn_object: '{{ { item.value.fqdn:  item.value.ip } }}'
            set_fact:
                fqdnIpDict: "{{ ( fqdnIpDict is defined and fqdnIpDict | combine(  fqdn_object )) or fqdn_object }}"
            with_dict: '{{ host_address }}'

        -
            name: '{{ step }} -  Validate DNS Resolutions'
            tags:
                - '{{ step }} - Validate DNS Resolutions'
            ehc_script_agent:
                package_name: common
                module_name: IValidateDNS
                method_name: validateDNSResolution
                method_params:
                    fqdnIpDict: '{{ fqdnIpDict }}'
                    hostDict: null
            register: validateDNSResolutionResults
            ignore_errors: '{{ ignore_errors|default(False) }}'


        # Prefer assert over json_query to display error better
        -
            name: '{{ step }} -  Check DNS Resolution Results'
            tags:
                - '{{ step }} - Validate DNS Resolutions'
            assert:
                that:
                    - '{{item.ForwardLookup}} and {{item.ReverseLookup}}'
            with_items: '{{validateDNSResolutionResults.data[1]}}'
            ignore_errors: '{{ ignore_errors|default(False) }}'
