# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
# Task file: pre-validation-input.yml
-
    name: '{{ step }} - Pre Validation - Input Data'
    hosts: localhost
    gather_facts: no
    any_errors_fatal: True
    tags:
              -   "{{ step }} - Validate Input data"
    tasks:
      -
          name: "{{ step }} -  Validate Input data for Virtual Machines"
          assert:
              that:
                  - 'item.value.fqdn|default(None) != ""'
                  - 'item.value.ip|default(None) != ""'
                  - 'item.value.ip|default(None) | ipaddr'
              msg: "Undefined or Invalid FQDN/IP for {{ item.key }} ; FQDN - {{ item.value.fqdn|default(None) }} ; IP - {{ item.value.ip|default(None) }}"
          with_dict: "{{ host_address }}"
          ignore_errors: '{{ ignore_errors|default(False) }}'

      -
          name: "{{ step }} -  Validate Input data for User Accounts"
          assert:
              that:
                  - 'item.value.username|default(None) != ""'
                  - 'item.value.password|default(None) != ""'
              msg: "Undefined Username/Password for {{ item.key }} ; Username - {{ item.value.username|default(None) }} ; Password - NOT LOGGED"
          with_dict: "{{ ad_user }}"
          ignore_errors: '{{ ignore_errors|default(False) }}'

      -
          name: "{{ step }} -  Validate Input data for User Groups"
          assert:
              that:
                  - 'item.value.groupname|default(None) != ""'
              msg: "Undefined Groupname for {{ item.key }} ; Groupname - {{ item.value.groupname|default(None) }}"
          with_dict: "{{ ad_user_group }}"
          ignore_errors: '{{ ignore_errors|default(False) }}'
