# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

# Active directory user group membership map
ad_user_group_membership:
    -
      name: ehc_system_admins
      members: [ ehc_sysadmin ]
    -
      name: ehc_fabric_admins
      members: [ehc_fabric_admin, app_vrops_vra]
    -
      name: ehc_iaas_admins
      members: [app_vrops_vra, ehc_iaas_admin]
    -
      name: ehc_tenant_admins
      members: [app_vrops_vra, ehc_tenant_admin]
    -
      name: nsx_ent_admins
      members: [ app_vra_nsx, app_vro_nsx, ehc_nsx_ent_admin ]

    -
      name: vc_admins
      members: [ ehc_vc_admin ]
    -
      name: vc_readonly
      members: [ ehc_nsx_ent_admin ]
    -
      name: vc_app_logins_rw
      members: [ svc_vcenter,app_nsx_vcenter,app_logi_vcenter,app_vra_vcenter,app_vro_vcenter,app_vrops_vcenter,app_vra_vro ]
    -
      name: vc_app_logins_ro
      members: [ app_vrb_vcenter,adp_vrops_vcenter ]
    -
      name: sso_admins
      members: [ app_nsx_sso,app_vra_sso,app_vro_sso ]
    -
      name: vro_admins
      members: [ app_vro_vcenter,app_vro_sso,app_vra_vro,app_vro_rest,ehc_vro_admin ]
    -
      name: sql_admins
      members: [ svc_iaas,ehc_sql_admin ]
    -
      name: sql_app_logins_ro
      members: [ app_vro_sql ]
    -
      name: vrops_admins
      members: [ ehc_vrops_admin ]
    -
      name: vrops_app_logins_rw
      members: [ app_logi_vrops ]
    -
      name: ehc_app_admins
      members: [ ehc_app_admin ]


# Active Directory Group Membership map
ad_nested_group_membership:
    -
      name: ehc_system_admins
      parent_groups: [ehc_xaas_architects ,ehc_fabric_admins ,ehc_iaas_admins ,tenant_bg_managers ,ehc_tenant_admins ,nsx_ent_admins ,vc_admins ,vc_app_logins_rw ,sso_admins , vro_admins ,sql_admins ,vrops_admins ,vrops_app_logins_rw ,log_insight_admins, ehc_app_admins]