# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

# https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx

windows_time_zones:
  Dateline Standard Time: '001'
  Samoa Standard Time: '000'
  Hawaiian Standard Time: '003'
  Alaskan Standard Time: '002'
  Pacific Standard Time: '004' 
  Mountain Standard Time: '010' 
  Mexico Standard Time 2: '013' 
  U.S. Mountain Standard Time: '015' 
  Central Standard Time: '020' 
  Canada Central Standard Time: '025' 
  Mexico Standard Time: '030' 
  Central America Standard Time: '033' 
  Eastern Standard Time: '035' 
  U.S. Eastern Standard Time: '040' 
  S.A. Pacific Standard Time: '045' 
  Atlantic Standard Time: '050' 
  S.A. Western Standard Time: '055' 
  Pacific S.A. Standard Time: '056' 
  Newfoundland and Labrador Standard Time: '060' 
  E. South America Standard Time: '065' 
  S.A. Eastern Standard Time: '070' 
  Greenland Standard Time: '073' 
  Mid-Atlantic Standard Time: '075' 
  Azores Standard Time: '080' 
  Cape Verde Standard Time: '083' 
  GMT Standard Time: '085' 
  Greenwich Standard Time: '090' 
  Central Europe Standard Time: '095' 
  Central European Standard Time: '100' 
  Romance Standard Time: '105' 
  W. Europe Standard Time: '110' 
  W. Central Africa Standard Time: '113' 
  E. Europe Standard Time: '115' 
  Egypt Standard Time: '120' 
  FLE Standard Time: '125' 
  GTB Standard Time: '130' 
  Israel Standard Time: '135' 
  South Africa Standard Time: '140' 
  Russian Standard Time: '145' 
  Arab Standard Time: '150' 
  E. Africa Standard Time: '155' 
  Arabic Standard Time: '158' 
  Iran Standard Time: '160' 
  Arabian Standard Time: '165' 
  Caucasus Standard Time: '170' 
  Transitional Islamic State of Afghanistan Standard Time: '175' 
  Ekaterinburg Standard Time: '180' 
  West Asia Standard Time: '185' 
  India Standard Time: '190' 
  Nepal Standard Time: '193' 
  Central Asia Standard Time: '195' 
  Sri Lanka Standard Time: '200' 
  N. Central Asia Standard Time: '201' 
  Myanmar Standard Time: '203' 
  S.E. Asia Standard Time: '205' 
  North Asia Standard Time: '207' 
  China Standard Time: '210' 
  Singapore Standard Time: '215' 
  Taipei Standard Time: '220' 
  W. Australia Standard Time: '225' 
  North Asia East Standard Time: '227' 
  Korea Standard Time: '230' 
  Tokyo Standard Time: '235' 
  Yakutsk Standard Time: '240' 
  A.U.S. Central Standard Time: '245' 
  Cen. Australia Standard Time: '250' 
  A.U.S. Eastern Standard Time: '255' 
  E. Australia Standard Time: '260' 
  Tasmania Standard Time: '265' 
  Vladivostok Standard Time: '270' 
  West Pacific Standard Time: '275' 
  Central Pacific Standard Time: '280' 
  Fiji Islands Standard Time: '285' 
  New Zealand Standard Time: '290' 
  Tonga Standard Time: '300' 

windows_linux_timezone_map:
  Samoa Standard Time:	Pacific/Apia
  Hawaiian Standard Time:	Pacific/Honolulu
  Alaskan Standard Time:	America/Anchorage
  Pacific Standard Time:	America/Los_Angeles
  Mountain Standard Time:	America/Denver
  Mexico Standard Time 2:	America/Mexico_City
  U.S. Mountain Standard Time:	America/Phoenix
  Central Standard Time:	America/Chicago
  Canada Central Standard Time:	America/Regina
  Mexico Standard Time:	America/Mexico_City
  Central America Standard Time:	America/Guatemala
  Eastern Standard Time:	America/New_York
  U.S. Eastern Standard Time:	US/Eastern
  S.A. Pacific Standard Time:	America/Bogota
  Atlantic Standard Time:	America/Halifax
  S.A. Western Standard Time:	America/La_Paz
  Pacific S.A. Standard Time:	America/Santiago
  Newfoundland and Labrador Standard Time:	America/St_Johns
  E. South America Standard Time:	America/Sao_Paulo
  S.A. Eastern Standard Time:	America/Cayenne
  Greenland Standard Time:	America/Godthab
  Mid-Atlantic Standard Time:	Atlantic/South_Georgia
  Azores Standard Time:	Atlantic/Azores
  Cape Verde Standard Time:	Atlantic/Cape_Verde
  GMT Standard Time:	Europe/London
  Greenwich Standard Time:	Atlantic/Reykjavik
  Central Europe Standard Time:	Europe/Budapest
  Central European Standard Time:	Europe/Warsaw
  Romance Standard Time:	Europe/Paris
  W. Europe Standard Time:	Europe/Berlin
  W. Central Africa Standard Time:	Africa/Lagos
  E. Europe Standard Time:	Europe/Chisinau
  Egypt Standard Time:	Africa/Cairo
  FLE Standard Time:	Europe/Kiev
  GTB Standard Time:	Europe/Bucharest
  Israel Standard Time:	Asia/Jerusalem
  South Africa Standard Time:	Africa/Johannesburg
  Russian Standard Time:	Europe/Moscow
  Arab Standard Time:	Asia/Riyadh
  E. Africa Standard Time:	Africa/Nairobi
  Arabic Standard Time:	Asia/Baghdad
  Iran Standard Time:	Asia/Tehran
  Arabian Standard Time:	Asia/Dubai
  Caucasus Standard Time:	Asia/Yerevan
  Transitional Islamic State of Afghanistan Standard Time:	Asia/Kabul
  Ekaterinburg Standard Time:	Asia/Yekaterinburg
  West Asia Standard Time:	Asia/Tashkent
  India Standard Time:	Asia/Kolkata
  Nepal Standard Time:	Asia/Kathmandu
  Central Asia Standard Time:	Asia/Almaty
  Sri Lanka Standard Time:	Asia/Colombo
  N. Central Asia Standard Time:	Asia/Novosibirsk
  Myanmar Standard Time:	Asia/Yangon
  S.E. Asia Standard Time:	Asia/Bangkok
  North Asia Standard Time:	Asia/Krasnoyarsk
  China Standard Time:	Asia/Shanghai
  Singapore Standard Time:	Asia/Singapore
  Taipei Standard Time:	Asia/Taipei
  W. Australia Standard Time:	Australia/Perth
  North Asia East Standard Time:	Asia/Irkutsk
  Korea Standard Time:	Asia/Seoul
  Tokyo Standard Time:	Asia/Tokyo
  Yakutsk Standard Time:	Asia/Yakutsk
  A.U.S. Central Standard Time:	Australia/Darwin
  Cen. Australia Standard Time:	Australia/Adelaide
  A.U.S. Eastern Standard Time:	Australia/Sydney
  E. Australia Standard Time:	Australia/Brisbane
  Tasmania Standard Time:	Australia/Hobart
  Vladivostok Standard Time:	Asia/Vladivostok
  West Pacific Standard Time:	Pacific/Port_Moresby
  Central Pacific Standard Time:	Pacific/Guadalcanal
  Fiji Islands Standard Time:	Pacific/Fiji
  New Zealand Standard Time:	Pacific/Auckland
  Tonga Standard Time:	Pacific/Tongatapu


vmware_time_zones:
   - Africa/Abidjan
   - Africa/Accra
   - Africa/Addis_Ababa
   - Africa/Algiers
   - Africa/Asmara
   - Africa/Bamako
   - Africa/Bangui
   - Africa/Banjul
   - Africa/Bissau
   - Africa/Blantyre
   - Africa/Brazzaville
   - Africa/Bujumbura
   - Africa/Cairo
   - Africa/Casablanca
   - Africa/Ceuta
   - Africa/Conakry
   - Africa/Dakar
   - Africa/Dar_es_Salaam
   - Africa/Djibouti
   - Africa/Douala
   - Africa/El_Aaiun
   - Africa/Freetown
   - Africa/Gaborone
   - Africa/Harare
   - Africa/Johannesburg
   - Africa/Juba
   - Africa/Kampala
   - Africa/Khartoum
   - Africa/Kigali
   - Africa/Kinshasa
   - Africa/Lagos
   - Africa/Libreville
   - Africa/Lome
   - Africa/Luanda
   - Africa/Lubumbashi
   - Africa/Lusaka
   - Africa/Malabo
   - Africa/Maputo
   - Africa/Maseru
   - Africa/Mbabane
   - Africa/Mogadishu
   - Africa/Monrovia
   - Africa/Nairobi
   - Africa/Ndjamena
   - Africa/Niamey
   - Africa/Nouakchott
   - Africa/Ouagadougou
   - Africa/Porto-Novo
   - Africa/Sao_Tome
   - Africa/Tripoli
   - Africa/Tunis
   - Africa/Windhoek
   - America/Adak
   - America/Anchorage
   - America/Anguilla
   - America/Antigua
   - America/Araguaina
   - America/Argentina/Buenos_Aires
   - America/Argentina/Catamarca
   - America/Argentina/Cordoba
   - America/Argentina/Jujuy
   - America/Argentina/La_Rioja
   - America/Argentina/Mendoza
   - America/Argentina/Rio_Gallegos
   - America/Argentina/Salta
   - America/Argentina/San_Juan
   - America/Argentina/San_Luis
   - America/Argentina/Tucuman
   - America/Argentina/Ushuaia
   - America/Aruba
   - America/Asuncion
   - America/Atikokan
   - America/Bahia
   - America/Bahia_Banderas
   - America/Barbados
   - America/Belem
   - America/Belize
   - America/Blanc-Sablon
   - America/Boa_Vista
   - America/Bogota
   - America/Boise
   - America/Cambridge_Bay
   - America/Campo_Grande
   - America/Cancun
   - America/Caracas
   - America/Cayenne
   - America/Cayman
   - America/Chicago
   - America/Chihuahua
   - America/Costa_Rica
   - America/Creston
   - America/Cuiaba
   - America/Curacao
   - America/Danmarkshavn
   - America/Dawson
   - America/Dawson_Creek
   - America/Denver
   - America/Detroit
   - America/Dominica
   - America/Edmonton
   - America/Eirunepe
   - America/El_Salvador
   - America/Fort_Nelson
   - America/Fortaleza
   - America/Glace_Bay
   - America/Godthab
   - America/Goose_Bay
   - America/Grand_Turk
   - America/Grenada
   - America/Guadeloupe
   - America/Guatemala
   - America/Guayaquil
   - America/Guyana
   - America/Halifax
   - America/Havana
   - America/Hermosillo
   - America/Indiana/Indianapolis
   - America/Indiana/Knox
   - America/Indiana/Marengo
   - America/Indiana/Petersburg
   - America/Indiana/Tell_City
   - America/Indiana/Vevay
   - America/Indiana/Vincennes
   - America/Indiana/Winamac
   - America/Inuvik
   - America/Iqaluit
   - America/Jamaica
   - America/Juneau
   - America/Kentucky/Louisville
   - America/Kentucky/Monticello
   - America/Kralendijk
   - America/La_Paz
   - America/Lima
   - America/Los_Angeles
   - America/Lower_Princes
   - America/Maceio
   - America/Managua
   - America/Manaus
   - America/Marigot
   - America/Martinique
   - America/Matamoros
   - America/Mazatlan
   - America/Menominee
   - America/Merida
   - America/Metlakatla
   - America/Mexico_City
   - America/Miquelon
   - America/Moncton
   - America/Monterrey
   - America/Montevideo
   - America/Montserrat
   - America/Nassau
   - America/New_York
   - America/Nipigon
   - America/Nome
   - America/Noronha
   - America/North_Dakota/Beulah
   - America/North_Dakota/Center
   - America/North_Dakota/New_Salem
   - America/Ojinaga
   - America/Panama
   - America/Pangnirtung
   - America/Paramaribo
   - America/Phoenix
   - America/Port-au-Prince
   - America/Port_of_Spain
   - America/Porto_Velho
   - America/Puerto_Rico
   - America/Rainy_River
   - America/Rankin_Inlet
   - America/Recife
   - America/Regina
   - America/Resolute
   - America/Rio_Branco
   - America/Santarem
   - America/Santiago
   - America/Santo_Domingo
   - America/Sao_Paulo
   - America/Scoresbysund
   - America/Sitka
   - America/St_Barthelemy
   - America/St_Johns
   - America/St_Kitts
   - America/St_Lucia
   - America/St_Thomas
   - America/St_Vincent
   - America/Swift_Current
   - America/Tegucigalpa
   - America/Thule
   - America/Thunder_Bay
   - America/Tijuana
   - America/Toronto
   - America/Tortola
   - America/Vancouver
   - America/Whitehorse
   - America/Winnipeg
   - America/Yakutat
   - America/Yellowknife
   - Antarctica/Casey
   - Antarctica/Davis
   - Antarctica/DumontDUrville
   - Antarctica/Macquarie
   - Antarctica/Mawson
   - Antarctica/McMurdo
   - Antarctica/Palmer
   - Antarctica/Rothera
   - Antarctica/Syowa
   - Antarctica/Troll
   - Antarctica/Vostok
   - Arctic/Longyearbyen
   - Asia/Aden
   - Asia/Almaty
   - Asia/Amman
   - Asia/Anadyr
   - Asia/Aqtau
   - Asia/Aqtobe
   - Asia/Ashgabat
   - Asia/Baghdad
   - Asia/Bahrain
   - Asia/Baku
   - Asia/Bangkok
   - Asia/Barnaul
   - Asia/Beirut
   - Asia/Bishkek
   - Asia/Brunei
   - Asia/Chita
   - Asia/Choibalsan
   - Asia/Colombo
   - Asia/Damascus
   - Asia/Dhaka
   - Asia/Dili
   - Asia/Dubai
   - Asia/Dushanbe
   - Asia/Gaza
   - Asia/Hebron
   - Asia/Ho_Chi_Minh
   - Asia/Hong_Kong
   - Asia/Hovd
   - Asia/Irkutsk
   - Asia/Jakarta
   - Asia/Jayapura
   - Asia/Jerusalem
   - Asia/Kabul
   - Asia/Kamchatka
   - Asia/Karachi
   - Asia/Kathmandu
   - Asia/Khandyga
   - Asia/Kolkata
   - Asia/Krasnoyarsk
   - Asia/Kuala_Lumpur
   - Asia/Kuching
   - Asia/Kuwait
   - Asia/Macau
   - Asia/Magadan
   - Asia/Makassar
   - Asia/Manila
   - Asia/Muscat
   - Asia/Nicosia
   - Asia/Novokuznetsk
   - Asia/Novosibirsk
   - Asia/Omsk
   - Asia/Oral
   - Asia/Phnom_Penh
   - Asia/Pontianak
   - Asia/Pyongyang
   - Asia/Qatar
   - Asia/Qyzylorda
   - Asia/Riyadh
   - Asia/Sakhalin
   - Asia/Samarkand
   - Asia/Seoul
   - Asia/Shanghai
   - Asia/Singapore
   - Asia/Srednekolymsk
   - Asia/Taipei
   - Asia/Tashkent
   - Asia/Tbilisi
   - Asia/Tehran
   - Asia/Thimphu
   - Asia/Tokyo
   - Asia/Tomsk
   - Asia/Ulaanbaatar
   - Asia/Urumqi
   - Asia/Ust-Nera
   - Asia/Vientiane
   - Asia/Vladivostok
   - Asia/Yakutsk
   - Asia/Yangon
   - Asia/Yekaterinburg
   - Asia/Yerevan
   - Atlantic/Azores
   - Atlantic/Bermuda
   - Atlantic/Canary
   - Atlantic/Cape_Verde
   - Atlantic/Faroe
   - Atlantic/Madeira
   - Atlantic/Reykjavik
   - Atlantic/South_Georgia
   - Atlantic/St_Helena
   - Atlantic/Stanley
   - Australia/Adelaide
   - Australia/Brisbane
   - Australia/Broken_Hill
   - Australia/Currie
   - Australia/Darwin
   - Australia/Eucla
   - Australia/Hobart
   - Australia/Lindeman
   - Australia/Lord_Howe
   - Australia/Melbourne
   - Australia/Perth
   - Australia/Sydney
   - Canada/Atlantic
   - Canada/Central
   - Canada/Eastern
   - Canada/Mountain
   - Canada/Newfoundland
   - Canada/Pacific
   - Europe/Amsterdam
   - Europe/Andorra
   - Europe/Astrakhan
   - Europe/Athens
   - Europe/Belgrade
   - Europe/Berlin
   - Europe/Bratislava
   - Europe/Brussels
   - Europe/Bucharest
   - Europe/Budapest
   - Europe/Busingen
   - Europe/Chisinau
   - Europe/Copenhagen
   - Europe/Dublin
   - Europe/Gibraltar
   - Europe/Guernsey
   - Europe/Helsinki
   - Europe/Isle_of_Man
   - Europe/Istanbul
   - Europe/Jersey
   - Europe/Kaliningrad
   - Europe/Kiev
   - Europe/Kirov
   - Europe/Lisbon
   - Europe/Ljubljana
   - Europe/London
   - Europe/Luxembourg
   - Europe/Madrid
   - Europe/Malta
   - Europe/Mariehamn
   - Europe/Minsk
   - Europe/Monaco
   - Europe/Moscow
   - Europe/Oslo
   - Europe/Paris
   - Europe/Podgorica
   - Europe/Prague
   - Europe/Riga
   - Europe/Rome
   - Europe/Samara
   - Europe/San_Marino
   - Europe/Sarajevo
   - Europe/Simferopol
   - Europe/Skopje
   - Europe/Sofia
   - Europe/Stockholm
   - Europe/Tallinn
   - Europe/Tirane
   - Europe/Ulyanovsk
   - Europe/Uzhgorod
   - Europe/Vaduz
   - Europe/Vatican
   - Europe/Vienna
   - Europe/Vilnius
   - Europe/Volgograd
   - Europe/Warsaw
   - Europe/Zagreb
   - Europe/Zaporozhye
   - Europe/Zurich
   - GMT
   - Indian/Antananarivo
   - Indian/Chagos
   - Indian/Christmas
   - Indian/Cocos
   - Indian/Comoro
   - Indian/Kerguelen
   - Indian/Mahe
   - Indian/Maldives
   - Indian/Mauritius
   - Indian/Mayotte
   - Indian/Reunion
   - Pacific/Apia
   - Pacific/Auckland
   - Pacific/Bougainville
   - Pacific/Chatham
   - Pacific/Chuuk
   - Pacific/Easter
   - Pacific/Efate
   - Pacific/Enderbury
   - Pacific/Fakaofo
   - Pacific/Fiji
   - Pacific/Funafuti
   - Pacific/Galapagos
   - Pacific/Gambier
   - Pacific/Guadalcanal
   - Pacific/Guam
   - Pacific/Honolulu
   - Pacific/Johnston
   - Pacific/Kiritimati
   - Pacific/Kosrae
   - Pacific/Kwajalein
   - Pacific/Majuro
   - Pacific/Marquesas
   - Pacific/Midway
   - Pacific/Nauru
   - Pacific/Niue
   - Pacific/Norfolk
   - Pacific/Noumea
   - Pacific/Pago_Pago
   - Pacific/Palau
   - Pacific/Pitcairn
   - Pacific/Pohnpei
   - Pacific/Port_Moresby
   - Pacific/Rarotonga
   - Pacific/Saipan
   - Pacific/Tahiti
   - Pacific/Tarawa
   - Pacific/Tongatapu
   - Pacific/Wake
   - Pacific/Wallis
   - US/Alaska
   - US/Arizona
   - US/Central
   - US/Eastern
   - US/Hawaii
   - US/Mountain
   - US/Pacific
   - UTC