global_ui_address:
    https://auto-dedicate.apps.cf.pie.lab.emc.com
primary_user:
    username: cyan.ni@emc.com
    password: password
    role: manager
secondary_user:
    username: wesley.peng@emc.com
    password: password
    role: developer
history_dir:
    /root/automation/bdl/history/
to_create_workspace_names:
    ['Cyan_Test']
created_workspace_names:
    ['GSE-Test-2', 'GSE-Test-1']
search_tools_name:
    {'AssetVisibleName': ['plan_002']}
services_to_be_deployed:
    {'MySQL for Pivotal Cloud Foundry': ['mysql_4_pcf']}
deployed_services:
    []
tools_to_be_deployed:
    {'Ma Testing': ['default']}
datasets_to_be_deployed:
    [{'AssetVisibleName': 'test publish data set5',
    'DataContainer': 'mysql_4_pcf',
    'WorkingSetName': 'automation',
    'TableName': 'automation_table'
    },]
deployed_datasets:
    []
collaborators_to_be_added:
    [{'username': 'wesley.peng@emc.com',
    'password': password,
    'role': 'developer',
    },]
added_collaborators:
    []
search_data_sets:
    {'AssetVisibleName': ['will-test1'],
    'AssetPublishedDate': ['2016-04-08 07:17:37'],
    'AssetRegisteredDate': ['2016-04-08 05:46:03'],
    'TemplateType': ['csv']
    }
tool_to_be_published:
    'auto test'
data_set_to_be_deleted:
    'test publish data set'
data_set_to_be_published:
    'test publish data set'
working_set_to_be_deleted:
    'test publish data set'
dac_service:
    restservice-auto.apps.cf.pie.lab.emc.com
dac_cli_address:
    10.102.6.218
dac_cli_username:
    root
dac_cli_password:
    '123456'
pcf_info:
    {
    'organization': 'fbdl-qa',
    'api_url': 'https://api.sd.cf.pie.lab.emc.com',
    'uaa_url': 'https://uaa.sd.cf.pie.lab.emc.com'
    }
vSphere_info:
    {
    'host_address': '10.102.7.182',
    'username': 'administrator@vsphere.local',
    'password': 'Password123!',
    'port': 443
    }
deployed_data_sets_guid:
    [
    '79419cc2-de61-418e-b7fc-311a6da24e1b',
    'b5e684e1-1200-45bd-ba75-f920c4fb15fb'
    ]
deployed_apps_guid:
    [
    ]