workflow_context:
    assets_info:
        [{
            'local_path': '/root/automation/bdl/asset/',
            'remote_path': '/tmp/',
            'file_name': 'dir',
            'visible_name': 'Auto_Dir_Asset'
         }]
