NAT_VM:
  SERVER_IP:  '' #Mandatory -  NAT Server IP
  SERVER_USERNAME: '' #Mandatory - NAT machine Username
  SERVER_PASSWORD: '' #Mandatory - NAT machine Password
  CERTIFICATE_COPY_LOCATION: '/tmp/'

TAS_DETAILS:
  TAS_IP: ''
  TAS_USER: 'tas'
  TAS_PWD:  'xStream2015!'
  CONFIG_YAML_PATH:  '/opt/tas/tenant_automation_service/config.yaml'
  TENANT_ID: ''
  EXPECTED_NW_VERSION: '9.1'

MW_DETAILS:
  MW_IP: ''
  MW_USER:  'tas'
  MW_PWD:  'xStream2015!'
  MW_CONFIG_YAML_PATH:  '/opt/middleware/middleware_service/config.yaml'
  WORKER_CONFIG_YAML_PATH:  '/opt/middleware/worker/config.yaml'
  SWAGGER_USER: 'middleware'
  SWAGGER_PWD: 'Password1'
  TENANT_ID: ''

VM_DETAILS:
  VMID: '11deef11-a111-1ae1-1fed-b1c1011111aa'
  VMHOSTNAME: 'rhel6.dummy.local'
  VM_IP: '1.1.1.1'
  RETENTION_TYPE: 'Days'
  RETENTION_DAYS: '15'
  CALLBACKURL:  'http://dummy_callback.com'
  LINUX_POLICY_ID:  '19'
  WIN_POLICY_ID: '6'
  TASKID: 'dummy001'
