BB_SERVER:
      SERVER_IP: "10.100.249.47"
      SERVER_USERNAME: "root"
      SERVER_PASSWORD: "Password1"
      TENANT_ID: '2812ea87-4116-4e83-b8cc-8687cf129972'
      DNS_NAME: 'BB-Server.xstest.local'
      RID: 'RK5'
      CLIENT_CERTIFICATES_PATH: '/etc/bridgeburner/certs/Virtustream/clients/'
      CLIENT_CERTIFICATES:  ['RK5.crt', 'RK5.key']
      CA_CERTIFICATES_PATH: '/etc/bridgeburner/certs/Virtustream/'
      CA_CERTIFICATES: ['CA.crt']
      LOCAL_FILE_LOCATION:  'C:/Users/madduv/Desktop/' #Local path to save the certiificates

BB_CLIENT:
      CLIENT_IP: "10.100.249.33"
      CLIENT_USERNAME: "root"
      CLIENT_PASSWORD: "Password1"
      REMOTE_CLIENT_CERTIFICATE_LOCATION: '/etc/bridgeburner/certs/Virtustream/clients/'
      REMOTE_CA_CERTIFICATE_LOCATION: '/etc/bridgeburner/certs/Virtustream/'
      OS_VERSION: 'centos6' #centos6 or centos7 or suse12 or rhel7

