# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

# Location of generated certificates
service_cert_file_path:
     nsx_manager: certs/{{ host_address.nsx_manager.fqdn }}-nsxmgr-svc/nsxmgr-svc-{{ host_address.nsx_manager.fqdn }}.pfx
     psc01_machinessl_svc: certs/{{ host_address.psc01.fqdn }}-psc-machinessl-svc/psc-machinessl-svc-{{ host_address.psc01.fqdn }}.cer
     psc01_machine_svc: certs/{{ host_address.psc01.fqdn }}-psc-machine-svc/psc-machine-svc-{{ host_address.psc01.fqdn }}.cer
     psc01_vsphere_webclient_svc: certs/{{ host_address.psc01.fqdn }}-psc-vsphere-webclient-svc/psc-vsphere-webclient-svc-{{ host_address.psc01.fqdn }}.cer
     psc02_machinessl_svc: certs/{{ host_address.psc02.fqdn }}-psc-machinessl-svc/psc-machinessl-svc-{{ host_address.psc02.fqdn }}.cer
     psc02_machine_svc: certs/{{ host_address.psc02.fqdn }}-psc-machine-svc/psc-machine-svc-{{ host_address.psc02.fqdn }}.cer
     psc02_vsphere_webclient_svc: certs/{{ host_address.psc02.fqdn }}-psc-vsphere-webclient-svc/psc-vsphere-webclient-svc-{{ host_address.psc02.fqdn }}.cer

     autopsc01_machinessl_svc: certs/{{ host_address.autopsc01.fqdn }}-psc-machinessl-svc/psc-machinessl-svc-{{ host_address.autopsc01.fqdn }}.cer
     autopsc01_machine_svc: certs/{{ host_address.autopsc01.fqdn }}-psc-machine-svc/psc-machine-svc-{{ host_address.autopsc01.fqdn }}.cer
     autopsc01_vsphere_webclient_svc: certs/{{ host_address.autopsc01.fqdn }}-psc-vsphere-webclient-svc/psc-vsphere-webclient-svc-{{ host_address.autopsc01.fqdn }}.cer

     vcenter_machinessl_svc: certs/{{ vcenter.fqdn }}-machinessl-svc/machinessl-svc-{{ vcenter.fqdn }}.cer
     vcenter_machine_svc: certs/{{ vcenter.fqdn }}-machine-svc/machine-svc-{{ vcenter.fqdn }}.cer
     vcenter_vsphere_webclient_svc: certs/{{ vcenter.fqdn }}-vshpere-webclient-svc/vshpere-webclient-svc-{{ vcenter.fqdn }}.cer
     vcenter_vpxd_extension_svc: certs/{{ vcenter.fqdn }}-vpxd-extension-svc/vpxd-extension-svc-{{ vcenter.fqdn }}.cer
     vcenter_vpxd_svc: certs/{{ vcenter.fqdn }}-vpxd-svc/vpxd-svc-{{ vcenter.fqdn }}.cer

     vra_svc: certs/{{ host_address.vra_load_balancer.fqdn }}-vra-svc/vra-svc-{{ host_address.vra_load_balancer.fqdn }}.pem
     vra_iaasmgr_svc: certs/{{ host_address.vra_manager_load_balancer.fqdn }}-iaasmgr-svc/iaasmgr-svc-{{ host_address.vra_manager_load_balancer.fqdn }}.pem
     vra_iaasweb_svc: certs/{{ host_address.vra_web_load_balancer.fqdn }}-iaasweb-svc/iaasweb-svc-{{ host_address.vra_web_load_balancer.fqdn }}.pem

     vrb_svc: certs/{{ host_address.vr_business.fqdn }}-vrb-svc/vrb-svc-{{ host_address.vr_business.fqdn }}.pem
     vrli_svc: certs/{{ host_address.log_insight.fqdn }}-vrli-svc/vrli-svc-{{ host_address.log_insight.fqdn }}.pem
     vro_svc: certs/{{ host_address.vro_load_balancer.fqdn }}-vro-svc/vro-svc-{{ host_address.vro_load_balancer.fqdn }}.pem
     vrops_svc: certs/{{ host_address.vrops_manager.fqdn }}-vrops-svc/vrops-svc-{{ host_address.vrops_manager.fqdn }}.pem


psc01Certificates:
    #TODO Should these point to above created certificates or original certificates?
    #TODO What would the root cert file path be? PB7 format?
    machineSSLCert:
        certificateFilePath: '{{ service_cert_file_path.psc01_machinessl_svc }}'
        keyFilePath: '{{ repository.certs.psc01_machinessl_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    machineCert:
        certificateFilePath: '{{ service_cert_file_path.psc01_machine_svc }}'
        keyFilePath: '{{ repository.certs.psc01_machine_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    vsphereWebclientCert:
        certificateFilePath: '{{ service_cert_file_path.psc01_vsphere_webclient_svc }}'
        keyFilePath: '{{ repository.certs.psc01_vsphere_web_client_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'

psc02Certificates:
    #TODO Should these point to above created certificates or original certificates?
    #TODO What would the root cert file path be? PB7 format?
    machineSSLCert:
        certificateFilePath: '{{ service_cert_file_path.psc02_machinessl_svc }}'
        keyFilePath: '{{ repository.certs.psc02_machinessl_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    machineCert:
        certificateFilePath: '{{ service_cert_file_path.psc02_machine_svc }}'
        keyFilePath: '{{ repository.certs.psc02_machine_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    vsphereWebclientCert:
        certificateFilePath: '{{ service_cert_file_path.psc02_vsphere_webclient_svc }}'
        keyFilePath: '{{ repository.certs.psc02_vsphere_web_client_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'

autopsc01Certificates:
    #TODO Should these point to above created certificates or original certificates?
    #TODO What would the root cert file path be? PB7 format?
    machineSSLCert:
        certificateFilePath: '{{ service_cert_file_path.autopsc01_machinessl_svc }}'
        keyFilePath: '{{ repository.certs.autopsc01_machinessl_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    machineCert:
        certificateFilePath: '{{ service_cert_file_path.autopsc01_machine_svc }}'
        keyFilePath: '{{ repository.certs.autopsc01_machine_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    vsphereWebclientCert:
        certificateFilePath: '{{ service_cert_file_path.autopsc01_vsphere_webclient_svc }}'
        keyFilePath: '{{ repository.certs.autopsc01_vsphere_web_client_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'

vcenterCertificates:
    machineSSLCert:
        certificateFilePath: '{{ service_cert_file_path.vcenter_machinessl_svc }}'
        keyFilePath: '{{ repository.certs.vcenter_machinessl_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    machineCert:
        certificateFilePath: '{{ service_cert_file_path.vcenter_machine_svc }}'
        keyFilePath: '{{ repository.certs.vcenter_machine_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    vsphereWebclientCert:
        certificateFilePath: '{{ service_cert_file_path.vcenter_vsphere_webclient_svc }}'
        keyFilePath: '{{ repository.certs.vcenter_vshpere_webclient_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    vpxdCert:
        certificateFilePath: '{{ service_cert_file_path.vcenter_vpxd_svc }}'
        keyFilePath: '{{ repository.certs.vcenter_vpxd_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'
    vpxdExtensionCert:
        certificateFilePath: '{{ service_cert_file_path.vcenter_vpxd_extension_svc }}'
        keyFilePath: '{{ repository.certs.vcenter_vpxd_ext_svc_key_path }}'
        rootCertFilePath: '{{ repository.certs.root_cert_path }}'


certificates_params_dict:
    vcenter_server: '{{ vcenterCertificates }}'
    psc01: '{{ psc01Certificates }}'
    psc02: '{{ psc02Certificates }}'
    autopsc01: '{{ autopsc01Certificates }}'

local_certs_template_file: ../templates/certs.json.j2
remote_certs_config_file: conf/certificateConfig.json