-
    name: 'VCN - {{ step }} - Configure vCenter Roles for vRB'
    hosts: vcenter_server
    gather_facts: no
    any_errors_fatal: True
    tags:
                - 'VCN - {{ step }} - Configure vCenter Roles for vRB'
    tasks:
        -
            name: 'VCN - {{ step }} - Pre-Validate Configure vCenter Roles for vRB'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vcenter
                module_name: createVcenterRoleForVRB
                method_name: validateCreateVcenterRoleForVRB
                method_params:
                    vcenterDict: '{{ vcenter }}'
                    roleName: 'Read-Only-vRB'
                    domain: '{{ ad_domain_name | upper  }}'
                    userName: '{{ ad_user.app_vrb_vcenter.username }}'
            register: preValidateVcentervRBRoleResults
            failed_when: preValidateVcentervRBRoleResults|failed or not preValidateVcentervRBRoleResults.data is defined or preValidateVcentervRBRoleResults.data.err_message is defined or not preValidateVcentervRBRoleResults.data.status == true
            changed_when: preValidateVcentervRBRoleResults.data is defined and preValidateVcentervRBRoleResults.data.err_message is not defined and preValidateVcentervRBRoleResults.data.status == true
            ignore_errors: preValidateVcentervRBRoleResults.failed_when_result

        -
            name: 'VCN - {{ step }} - Configure vCenter Roles for vRB'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vcenter
                module_name: createVcenterRoleForVRB
                method_name: createVcenterRoleForVRB
                method_params:
                    vcenterDict: '{{ vcenter }}'
                    roleName: 'Read-Only-vRB'
                    domain: '{{ domainDict.domainName }}'
                    userName: '{{ ad_user.app_vrb_vcenter.username }}'
            register: configureVcenterVrbRolesResult
            failed_when: configureVcenterVrbRolesResult|failed or not configureVcenterVrbRolesResult.data is defined or configureVcenterVrbRolesResult.data.err_message is defined or not configureVcenterVrbRolesResult.data.status == true
            changed_when: configureVcenterVrbRolesResult.data is defined and configureVcenterVrbRolesResult.data.err_message is not defined and configureVcenterVrbRolesResult.data.status == true
            when: preValidateVcentervRBRoleResults.failed_when_result

        -
            name: 'VCN - {{ step }} - Validate Configure vCenter Roles for vRB'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vcenter
                module_name: createVcenterRoleForVRB
                method_name: validateCreateVcenterRoleForVRB
                method_params:
                    vcenterDict: '{{ vcenter }}'
                    roleName: 'Read-Only-vRB'
                    domain: '{{ ad_domain_name | upper  }}'
                    userName: '{{ ad_user.app_vrb_vcenter.username }}'
            register: validateVcenterVrbRolesResult
            failed_when: validateVcenterVrbRolesResult|failed or not validateVcenterVrbRolesResult.data is defined or validateVcenterVrbRolesResult.data.err_message is defined or not validateVcenterVrbRolesResult.data.status == true
            changed_when: validateVcenterVrbRolesResult.data is defined and validateVcenterVrbRolesResult.data.err_message is not defined and validateVcenterVrbRolesResult.data.status == true
            when: not configureVcenterVrbRolesResult|skipped