# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
# Playbook file: deploy.yml
-
    include:  plays/drs-management.yml
    vars:
        vms: vcenter_server
        step: VCN - EPB-150-010
        description: Configure DRS on Management Clusters
        automation_level: partially
-
    include:  plays/create-resource-pool.yml
    vars:
        vms: vcenter_server
        step: VCN - EPB-150-015

-
    include:  plays/create-windows-template.yml
    vars:
        # Using SQL Server IP and FQDN for deploying test VM
        vms: sql_server
        step: DEP - EPB-150-020

-
    include: plays/deploy-all-virtual-machines.yml
    vars:
        step: DEP - EPB-150-030

-   include: plays/configure-msdtc.yml vms='all_windows_servers' step='DEP - EPB-150-035'

-
    include: plays/add-hdds-to-windows-vms.yml
    vars:
        step: DEP - EPB-150-040

-
    include: ../backup_and_restore/plays/power-off-vms.yml
    vars:
        step: DEP - EPB-150-050
        vms: all_windows_servers

-
    include: plays/size-linux-vms.yml
    vars:
        step: DEP - EPB-150-060