# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------


#-   include: plays/wait-for-services.yml
#    vars:
#      step: VRO - EPB-400-000
#      vms: vro_servers

-   include: plays/setup-vro-cluster-configuration.yml
    vars:
      step: VRO - EPB-400-010

-   include: plays/wait-for-services.yml
    vars:
      step: VRO - EPB-400-010
      vms: vro_servers

-   include: plays/join-vro-node-to-cluster.yml
    vars:
      step: VRO - EPB-400-020
      vms: vro_secondary

-   include: plays/wait-for-services.yml
    vars:
      step: VRO - EPB-400-020
      vms: vro_servers

-
    include:  plays/reload-all-plugins.yml
    vars:
        step: VRO - EPB-400-030
        vms: vro_servers
        serial: 1

-
    include:  plays/install-workflow-packages.yml
    vars:
        step: VRO - EPB-400-040
        vms: vro_primary
        packages: '{{ packages_1set_set }}'

-
    include:  ../vrli/install-vrli-agent.yml
    vars:
        step: VRO - EPB-400-050
        vms: vro_servers
        log_insight_agent_file_path: '{{ hostvars["log_insight"].log_insight_linux_agent_file }}'
        vmDict: '{{ vroInfo }}'

-
    include:  plays/configure-vcenter-plugins.yml
    vars:
        step: VRO - EPB-400-060