# ------------------------------------------------------------------------------
# Copyright (C) 2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

- include: plays/datadomain-entry-prevalidation.yml step='DataDomain - EPB-900-000'
- include: plays/deploy.yml step='DataDomain - EPB-900-001' version=6.0
