# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    include:  plays/backup-nsx-native.yml
    vars:
        step: BKP - BPB-200-010
        vms: nsx_manager
# NOTE: backup path needs to exist on windows ftp site: constant.NSX_BACKUP_DIRECTORY
-
    include: plays/power-off-vms.yml
    vars:
        step: BKP - BPB-200-020
        vms: nsx_manager

-
    include: plays/power-off-vms.yml
    vars:
        step: BKP - BPB-200-030
        vms: nsx_load_balancers
-
    include:  plays/backup-snapshot.yml
    vars:
        step: BKP - BPB-200-040
        description: 'Snapshot Configure-vCenter-and-NSX'
        snapshot_name: BPB-200-Configure-vCenter-and-NSX
        snapshot_description: 'BPB-200-Configure-vCenter-and-NSX'
        # TODO: PSC02, autopsc is missing and missing LBs and
        vms: vcenter_servers,nsx_manager,nsx_servers,vrops_manager
        dumpMemory: True
        powerOffVM: False

-
    include:  plays/backup-postgres-db.yml
    vars:
        step: BKP - BPB-200-100
        fileNamePrefix: BPB-200-100
        vms: vcenter_server

-
    include:  plays/delete-snapshots-not-matching-name.yml
    vars:
        step: BKP - BPB-200-110
        vms: vcenter_server:psc01
        inventoryPath: 'Discovered virtual machine'
        snapshotName: BPB-200-Configure-vCenter-and-NSX

-
    include:  plays/delete-snapshots-not-matching-name.yml
    vars:
        step: BKP - BPB-200-130
        vms: nsx_manager
        inventoryPath: '/'
        snapshotName: BPB-200-Configure-vCenter-and-NSX

-
    include:  plays/delete-snapshots-not-matching-name.yml
    vars:
        step: BKP - BPB-200-140
        vms: vrops_manager
        inventoryPath: '/'
        snapshotName: BPB-200-Configure-vCenter-and-NSX

-
    include:  plays/delete-postgres-db.yml
    vars:
        step: BKP - BPB-200-150
        fileNamePrefix: BPB-200-100
        vms: vcenter_server

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-200-160
        vms: nsx_manager

-
    include: plays/poll-nsx-manager.yml
    vars:
        step: BKP - BPB-200-170
        vms: nsx_manager

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-200-180
        vms: nsx_load_balancers

# TODO: GAP - No poll for NSX Load Balancers

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-200-200
        vms: vrops_manager

-
    include: plays/poll-vrops.yml
    vars:
        step: BKP - BPB-200-210
        vms: vrops_manager