# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
-
    include: plays/power-off-vms.yml
    vars:
        step: BKP - BPB-400-010
        vms: vro_servers

-
    include: plays/backup-snapshot.yml
    vars:
        step: BKP - BPB-400-020
        description: 'Configure vRO'
        snapshot_name: BPB-400-CONFIGURE-VRO
        snapshot_description: BPB-400-CONFIGURE-VRO
        vms: vro_servers
        dumpMemory: True
        powerOffVM: False

-
    include:  plays/backup-sql-db.yml
    vars:
        step: BKP - BPB-400-030
        dbName: '{{ databases.vro_database }}'
        backupName: 'BPB-400-CONFIGURE-VRO.bak'
        vms: sql_server

-
    include:  plays/delete-snapshots-not-matching-name.yml
    vars:
        step: BKP - BPB-400-040
        vms: vro_servers
        inventoryPath: '/'
        snapshotName:  BPB-400-CONFIGURE-VRO

-
    include:  plays/delete-sql-db.yml
    vars:
        step: BKP - BPB-400-050
        dbName: '{{ databases.vro_database }}'
        backupName: 'BPB-400-CONFIGURE-VRO.bak'
        vms: sql_server

-
    include: plays/poll-sql-db.yml
    vars:
        step: BKP - BPB-400-060
        vms: sql_server
        dbName: '{{ databases.vro_database }}'

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-400-060
        vms: vro_servers

-
    include: plays/poll-vro.yml
    vars:
        step: BKP - BPB-400-080
        vms: vro_servers

# Poll Clustered VRO
-
    include: plays/poll-vro-cluster.yml
    vars:
        step: BKP - BPB-400-090
        vms: vro_servers