# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
-
    include: plays/power-off-vms.yml
    vars:
        step: BKP - BPB-450-010
        vms: nsx_load_balancers
        serial: 2

-
    include: plays/power-off-vms.yml
    vars:
        step: BKP - BPB-450-020
        vms: nsx_manager

-
    include: plays/power-off-vms.yml
    vars:
        step: BKP - BPB-450-030
        vms: vra_iaas_agent_servers,vra_iaas_worker_servers,vra_iaas_manager_servers,vra_iaas_web_servers,vra_servers
        serial: 2

-
    include: plays/backup-snapshot.yml
    vars:
        step: BKP - BPB-450-080
        description: 'Snapshot vRA Servers Offline'
        snapshot_name: BPB-450-CONFIGURE-VRA
        snapshot_description: BPB-450-CONFIGURE-VRA
        vms: nsx_servers,vra_iaas_agent_servers,vra_iaas_worker_servers,vra_iaas_manager_servers,vra_iaas_web_servers,vra_servers
        dumpMemory: True
        powerOffVM: False

-
    include:  plays/backup-sql-db.yml
    vars:
        step: BKP - BPB-450-150
        dbName: '{{ databases.vra_database }}'
        backupName: 'BPB-450-CONFIGURE-VRA.bak'
        vms: sql_server

-
    include:  plays/backup-sql-db.yml
    vars:
        step: BKP - BPB-450-155
        dbName: 'master'
        backupName: 'BPB-450-CONFIGURE-VRA.bak'
        vms: sql_server

-
    include: plays/delete-snapshots-not-matching-name.yml
    vars:
        step: BKP - BPB-450-160
        vms: nsx_servers,vra_iaas_agent_servers,vra_iaas_worker_servers,vra_iaas_manager_servers,vra_iaas_web_servers,vra_servers
        inventoryPath: '/'
        snapshotName:  BPB-450-CONFIGURE-VRA

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-450-330
        vms: nsx_manager

-
    include: plays/poll-nsx-manager.yml
    vars:
        step: BKP - BPB-450-340
        vms: nsx_manager

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-450-350
        vms: nsx_load_balancers

# TODO: Poll Load Balancers

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-450-230
        vms: vra_servers

-
    include: plays/poll-vra-5480.yml
    vars:
        step: BKP - BPB-450-240
        vms: vra_servers

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-450-250
        vms: vra_iaas_web_servers

-
    include: plays/poll-vra-web.yml
    vars:
        step: BKP - BPB-450-260
        vms: vra_iaas_web_servers

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-450-270
        vms: vra_iaas_manager_servers

-
    include: plays/poll-vra-manager.yml
    vars:
        step: BKP - BPB-450-280
        vms: vra_iaas_manager_servers

-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-450-290
        vms: vra_iaas_worker_servers

-
    include: plays/poll-vra-dem.yml
    vars:
        step: BKP - BPB-450-300
        vms: vra_iaas_worker_servers
-
    include: plays/power-on-vms.yml
    vars:
        step: BKP - BPB-450-310
        vms: vra_iaas_agent_servers

-
    include: plays/poll-vra-agent.yml
    vars:
        step: BKP - BPB-450-320
        vms: vra_iaas_agent_servers

-
    include: plays/poll-vra-app.yml
    vars:
        step: BKP - BPB-450-370
        vms: vra_servers

# TODO: Poll NSX LB - Gap
