# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
-
    include: plays/power-off-vms.yml
    vars:
        step: RPB - RPB-800-050
        vms: vra_iaas_agent_servers:vra_iaas_worker_servers:vra_iaas_manager_servers:vra_iaas_web_servers:vra_servers

-
    include: plays/restore-snapshot.yml
    vars:
        step: RPB - RPB-800-90
        description: 'Rollback-Configure-VRA'
        snapshot_name: BPB-800-CONFIGURE-VRA
        vms: vra_iaas_agent_servers:vra_iaas_worker_servers:vra_iaas_manager_servers:vra_iaas_web_servers:vra_servers

-
    include: plays/poll-sql-server.yml
    vars:
        step: RPB - RPB-800-140
        vms: sql_server
-
    include: plays/poll-sql-db.yml
    vars:
        step: RPB - RPB-800-150
        vms: sql_server
        dbName: '{{ databases.vro_database }}'

-
    include: plays/poll-sql-db.yml
    vars:
        step: RPB - RPB-800-160
        vms: sql_server
        dbName: '{{ databases.ehc_om_database }}'

-
    include: plays/poll-sql-db.yml
    vars:
        step: RPB - RPB-800-170
        vms: sql_server
        dbName: '{{ databases.vra_database }}'

-
    include: plays/power-on-vms.yml
    vars:
        step: RPB - RPB-800-180
        vms: vra_iaas_web_servers

-
    include: plays/poll-vra-web.yml
    vars:
        step: RPB - RPB-800-190
        vms: vra_iaas_web_servers

-
    include: plays/power-on-vms.yml
    vars:
        step: RPB - RPB-800-200
        vms: vra_manager_primary

-
    include: plays/poll-vra-manager.yml
    vars:
        step: RPB - RPB-800-210
        vms: vra_manager_primary

-
    include: plays/power-on-vms.yml
    vars:
        step: RPB - RPB-800-220
        vms: vra_iaas_worker_servers

-
    include: plays/poll-vra-dem.yml
    vars:
        step: RPB - RPB-800-230
        vms: vra_worker_primary
        
-
    include: plays/power-on-vms.yml
    vars:
        step: RPB - RPB-800-240
        vms: vra_iaas_agent_servers

-
    include: plays/poll-vra-agent.yml
    vars:
        step: RPB - RPB-800-250
        vms: vra_proxy_agent_primary