# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

---
-
    include: plays/power-off-vms.yml
    vars:
        step: RPB - RPB-450-050
        vms: vra_iaas_agent_servers:vra_iaas_worker_servers:vra_iaas_manager_servers:vra_iaas_web_servers:vra_servers
        description: vRA Servers
        serial: 2

-
    include: plays/power-off-vms.yml
    vars:
        step: RPB - RPB-450-100
        vms: nsx_load_balancers
        description: NSX Load Balancers

-
    include: plays/power-off-vms.yml
    vars:
        step: RPB - RPB-450-110
        vms: nsx_manager
        description: NSX Manager

# Note: Cant delete DB if SQL server is powered off
#-
#    include: plays/power-off-vms.yml
#    vars:
#        step: RPB - RPB-450-120
#        vms: sql_server
#        description: SQL Server

-
    include: plays/restore-snapshot.yml
    vars:
        step: RPB - RPB-450-110
        description: 'Rollback-Configure-VRA'
        snapshot_name: BPB-150-Deploy-Automation-Pod
        vms: vra_iaas_agent_servers:vra_iaas_worker_servers:vra_iaas_manager_servers:vra_iaas_web_servers:vra_servers

-
    include: plays/restore-snapshot.yml
    vars:
        step: RPB - RPB-450-180
        description: 'Rollback-Configure-NSX-Servers'
        snapshot_name: BPB-200-Configure-vCenter-and-NSX
        vms: nsx_servers


-
    include: plays/drop-sql-db.yml
    vars:
        step: RPB - RPB-450-200
        dbName: '{{  databases.vra_database  }}'
        vms: sql_server

-
    include: plays/power-on-vms.yml
    vars:
        step: RPB - RPB-450-210
        vms: nsx_manager
        description: NSX Manager

-
    include: plays/poll-nsx-manager.yml
    vars:
        step: RPB - RPB-450-220
        vms: nsx_manager

-
    include: plays/power-on-vms.yml
    vars:
        step: RPB - RPB-450-230
        vms: nsx_load_balancers
        description: NSX Load Balancers

# TODO: GAP - need a poll nsx_load_balancers - RPB-450-240

#-
#    include: plays/power-on-vms.yml
#    vars:
#        step: RPB - RPB-450-250
#        vms: sql_server
#        description: SQL Server

-
    include: plays/poll-sql-server.yml
    vars:
        step: RPB - RPB-450-260
        vms: sql_server

-
    include: plays/poll-sql-db.yml
    vars:
        step: RPB - RPB-450-270
        vms: sql_server
        dbName: '{{ databases.vro_database }}'
        description: vRO DB

-
    include: plays/poll-sql-db.yml
    vars:
        step: RPB - RPB-450-280
        vms: sql_server
        dbName: '{{ databases.ehc_om_database }}'
        description: EHCOM DB