# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: '{{ step|default(None) }} - Poll SQL Server'
    hosts: '{{ vms }}'
    serial: '{{ serial | default(20) }}'
    gather_facts: no
    any_errors_fatal: True
    tasks:
        -
            name: '{{ step|default(None) }} - Poll SQL Server'
            tags:
                - '{{ step|default(None) }} - Poll SQL Server'
            delegate_to: localhost
            run_once: true
            ehc_script_agent:
                package_name: common
                module_name: sqlUtils
                method_name: validateSQLConnectionAndPort
                method_params:
                    host: '{{ host_address.sql_server.ip }}'
            register: pollSQLServerResults
            failed_when: not pollSQLServerResults.data is defined or pollSQLServerResults.data.err_message is defined or not pollSQLServerResults.data.status == true
            changed_when: pollSQLServerResults.data is defined and not pollSQLServerResults.data.err_message is defined and pollSQLServerResults.data.status == true
            until: pollSQLServerResults.data is defined and not pollSQLServerResults.data.err_message is defined and pollSQLServerResults.data.status == true
            retries: '{{ poll_retries }}'
            delay: '{{ poll_delay }}'