# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: '{{ step }} - Poll Loginsight Appliances'
    hosts: '{{ vms }}'
    gather_facts: no
    any_errors_fatal: True
    tags:
        - '{{ step }} - Poll vRLI'
    tasks:
        -
            name: '{{ step }} - Poll vRLI'
            delegate_to: localhost
            ehc_script_agent:
                package_name: vrli
                module_name: pollvRealizeLogInsight
                method_name: pollvRealizeLogInsight
                method_params:
                    vRLIHost: '{{ ansible_host }}'
            register: pollvRLIResults
            failed_when: not pollvRLIResults.data is defined or pollvRLIResults.data.err_message is defined or not pollvRLIResults.data.status == true
            changed_when: pollvRLIResults.data is defined and pollvRLIResults.data.err_message is not defined and pollvRLIResults.data.status == true
            until: pollvRLIResults.data is defined and pollvRLIResults.data.err_message is not defined and pollvRLIResults.data.status == true
            retries: '{{ poll_retries }}'
            delay: '{{ poll_delay }}'