back_up_server_details:
    SERVER_IP: "10.100.249.44"
    SERVER_USERNAME: "root"
    SERVER_PASSWORD: "Password1"
    SSH_PORT_NUMBER: 22

middle_ware_vm:
      properties: {'IP_Address': '10.100.249.69', 'Subnet_Mask': '255.255.255.128',
                           'Default_Gateway': '10.100.249.1', 'Primary_DNS': '10.100.26.177',
                           'Http_Proxy': '10.131.236.9', 'Http_Proxy_Port': '3128',
                           'CONSUL_IP': '10.100.249.47', 'CONSUL_PORT': '8500', 'XSTREAM_IP': '10.100.249.35',
                           'XSTREAM_KEY': '',
                           'XSTREAM_SECRET': ''}
