# ------------------------------------------------------------------------------
# Copyright (C) 2016-2017 DELL EMC Corporation. All Rights Reserved.

# This software contains the intellectual property of DELL EMC Corporation
# or is licensed to DELL EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of DELL  EMC.

# ------------------------------------------------------------------------------

-
    name: 'CLN - {{ step }} - Archive Logs'
    hosts: sql_server
    any_errors_fatal: True
    vars:
      step: EPB-900-010
    tags:
      - 'CLN - {{ step }} - Archive Logs'
    tasks:
        -
            name: 'CLN - {{ step }} - Archive Logs'
            delegate_to: localhost
            ehc_script_agent:
                package_name: archive
                module_name: archiveLog
                method_name: archiveLog
                method_params:
                    vCenterDict: '{{ vcenter }}'
                    datastoreName: '{{ vcenter_datastore }}'
                    remoteFilePath: '/Backups'
            register: archiveLogResults
            failed_when: not archiveLogResults.data is defined or archiveLogResults.data.err_message is defined or archiveLogResults.data.status == false
            changed_when: archiveLogResults.data is defined and not archiveLogResults.data.err_message is defined and archiveLogResults.data.status == true
-
    name: 'CLN - {{ step }} - Archive SQL DB Backups'
    hosts: sql_server
    any_errors_fatal: True
    vars:
      step: EPB-900-020
    tags:
      - 'CLN - {{ step }} - Archive SQL DB Backups'
    tasks:
        -
            name: 'CLN - {{ step }} - Archive SQL DB Backups'
            delegate_to: localhost
            ehc_script_agent:
                package_name: sql
                module_name: archiveSqlDBBackups
                method_name: archiveSqlDatabaseBackups
                method_params:
                    vCenterInfo: '{{ vcenter }}'
                    databaseInfo:
                      sqlServer: '{{ host_address.sql_server.fqdn }}'
                      dbName: '{{ item }}'
                    datastoreName: '{{ vcenter_datastore }}'
            register: archiveSqlDatabaseBackupsResults
            failed_when: not archiveSqlDatabaseBackupsResults.data is defined or archiveSqlDatabaseBackupsResults.data.err_message is defined or archiveSqlDatabaseBackupsResults.data.status == false
            changed_when: archiveSqlDatabaseBackupsResults.data is defined and not archiveSqlDatabaseBackupsResults.data.err_message is defined and archiveSqlDatabaseBackupsResults.data.status == true
            with_items:
              - '{{ databases.vro_database }}'
              - '{{ databases.ehc_om_database }}'
              - '{{ databases.vra_database }}'

-
    name: 'CLN - {{ step }} - PostGres DB Backups'
    hosts: vcenter_server
    any_errors_fatal: True
    vars:
      step: EPB-900-030
    tags:
      - 'CLN - {{ step }} - PostGres DB Backups'
    tasks:
        -
            name: 'CLN - {{ step }} - PostGres DB Backups'
            delegate_to: localhost
            ehc_script_agent:
                package_name: sql
                module_name: archivePostgresDBBackups
                method_name: archivePostgresDatabaseBackups
                method_params:
                    vCenterInfo: '{{ vcenter }}'
                    databaseInfo:
                      postgresServer: '{{ vmname }}'
                      dbDirName: 'VCDB'
                    datastoreName: '{{ vcenter_datastore }}'
            register: archivePostgresDatabaseBackupsResults
            failed_when: not archivePostgresDatabaseBackupsResults.data is defined or archivePostgresDatabaseBackupsResults.data.err_message is defined or archivePostgresDatabaseBackupsResults.data.status == false
            changed_when: archivePostgresDatabaseBackupsResults.data is defined and not archivePostgresDatabaseBackupsResults.data.err_message is defined and archivePostgresDatabaseBackupsResults.data.status == true

-
    name: 'CLN - {{ step }} - Archive Orchestrator VM Logs'
    hosts: vcenter_server
    any_errors_fatal: True
    vars:
      step: EPB-900-035
    tags:
      - 'CLN - {{ step }} - Archive Orchestrator VM Logs'
    tasks:
        -
            name: 'CLN - {{ step }} - Archive Orchestrator VM Logs'
            delegate_to: localhost
            ehc_script_agent:
                package_name: archive
                module_name: downloadLogToDatastore
                method_name: downloadLogToDatastore
                method_params:
                    vCenterDict: '{{ vcenter }}'
                    vmDict: '{{ master_vm_dict }}'
                    remoteLogsFolder: '{{ orch_vm_data_path }}'
                    datastoreName: '{{ vcenter_datastore }}'
                    remotePathInDatastore: '/Backups'
            register: downloadLogToDatastoreResults
            failed_when: not downloadLogToDatastoreResults.data is defined or downloadLogToDatastoreResults.data.err_message is defined or downloadLogToDatastoreResults.data.status == false
            changed_when: downloadLogToDatastoreResults.data is defined and not downloadLogToDatastoreResults.data.err_message is defined and downloadLogToDatastoreResults.data.status == true

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-040
        vms: sql_server
        inventoryPath: '/'
        snapshotName:  BPB-250-CONFIGURE-SQL

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-041
        vms: vra_all_servers
        inventoryPath: '/'
        snapshotName:  BPB-750-CONFIGURE-VRA

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-042
        vms: vr_business_servers
        inventoryPath: '/'
        snapshotName:  BPB-600-CONFIGURE-VRB

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-043
        vms: log_insight_servers,log_insight_workers,log_insight_forwarders
        inventoryPath: '/'
        snapshotName:  BPB-650-CONFIGURE-LOGINSIGHT

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-044
        vms: vro_servers
        inventoryPath: '/'
        snapshotName:  BPB-700-Deploy-Configure-EHC-Foundation

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-045
        vms: vrops_servers,vrops_data_nodes,vrops_remote_collectors
        inventoryPath: '/'
        snapshotName:  BPB-550-CONFIGURE-VROPS


-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-046
        vms: nsx_servers
        inventoryPath: '/'
        snapshotName:  BPB-450-CONFIGURE-VRA

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-047
        vms: vcenter_server,psc01
        inventoryPath: '{{ vcenter_folderPath }}'
        snapshotName:  BPB-200-Configure-vCenter-and-NSX

-
    include: ../backup_and_restore/plays/delete-snapshot.yml
    vars:
        step: CLN - EPB-900-048
        vms: additional_pscs
        inventoryPath: '/'
        snapshotName:  BPB-200-Configure-vCenter-and-NSX

-   include: ../validation/plays/pre-validation-smtp.yml step="NTF - 900" subject="SUCCESS!! EHC Automated Install Successfull!" textInMail="The EHC Automated Install has finished successfully. Attempting to destroy the EHC Automated Install vAPP. For logs please check 'Backups' folder in the datastore." ignore_errors=True

-
    include: plays/destroy-vapp.yml
    vars:
        step: CLN - EPB-900-090

#-
#    include: ../backup_and_restore/plays/power-off-and-destroy-vms.yml
#    vars:
#        step: CLN - EPB-900-090
#        vms: ehc_install_worker
#        vmname: '{{ worker_vm_dict_vm_name }}'
#        inventoryPath: '/'